#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

$opts = getopt('b:');

$birthDate = $opts['b'] ?? '1973-09-09';

$days = new \Wandodin\Dates\BirthDays($birthDate);

$totalDays = $days->findTotalDays();

echo "$birthDate : $totalDays\n";
