#!/usr/bin/env php
<?php


$opts = getopt("b:");
//print_r($opts);

$birthDate = $opts['b'] ?? '1973-09-09';
$todayDate = date("Y-m-d");

$birthTime = strtotime($birthDate);
$todayTime = strtotime($todayDate);

$totalSecs = $todayTime - $birthTime;
$totalDays = floor($totalSecs / 3600 / 24);

echo "$birthDate : $totalDays\n";
